server:
  port: 8080
spring:
  datasource:
    # ─────── DataSource (JDBC) ───────
    url: jdbc:postgresql://localhost:5432/form
    username: postgres
    password: root

    # ─────── HikariCP pool settings ───────
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      auto-commit: false

  jpa:
    # ─────── JPA / Hibernate ───────
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

form:
  security:
    config:
      secret:
        key: wrZ97kPP_lxltSTDIVQYfiTcXpBG7eVwi-EKy0qXTXE
    api:
      key:
        refresh:
          timeout: 86_400_000   # 24h = 86,400,000ms
        access:
          timeout: 3_600_000    # 1h = 3,600,000ms
    cors:
      origins:
        allowed:
          - url: "http://localhost:8080"
            methods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
          - url: "http://127.0.0.1:8080"
            methods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH