server:
  port: 8080
spring:
  datasource:
    # ─────── DataSource (JDBC) ───────
    url: jdbc:postgresql://localhost:5432/form
    username: postgres
    password: root

    # ─────── HikariCP pool settings ───────
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000

  jpa:
    # ─────── JPA / Hibernate ───────
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

form:
  security:
    config:
      secrets:
        key: wrZ97kPP_lxltSTDIVQYfiTcXpBG7eVwi-EKy0qXTXE
    api:
      key:
        refresh:
          # refreshKeyTimeout (in milliseconds)
          timeout: 86_400_000   # e.g. 24h = 86,400,000ms
        access:
          # access timeout (in milliseconds)
          timeout: 3_600_000    # e.g. 1h = 3,600,000ms

      cors:
        allowed:
          origins: http://localhost:8080,http://127.0.0.1:8080
          methods: GET,POST,PUT,DELETE,PATCH